# Generated by Django 3.2.12 on 2022-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220401_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.TextField(blank=True),
        ),
    ]
