# Generated by Django 3.2.12 on 2022-04-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
